apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: 'nginx-deployment-${parameters.release}'
spec:
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: nginx
        release: '${parameters.release}'
    spec:
      containers:
        - image: 'nginx:1.7.9'
          name: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
	release: green
  type:NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: 3
  ui_properties_file_name: "user-interface.properties"
  #
  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
