apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'nginx-deployment-${parameters.release}'
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app: nginx
      release: '${parameters.release}'
  template:
    metadata:
      labels:
        app: nginx
        release: '${parameters.release}'
    spec:
      containers:
        - image: 'jsandy11/nginx:${parameters.release}'
          name: nginx
          ports:
            - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: "/config"
      volumes:
      - name: config
        configMap: 
          name: nginx-configmap
