apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
  - nodePort: 32420
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    release: green
  type:NodePort
